/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Assistant: typeof import('./components/Assistant.tsx')['default']
    Blogs: typeof import('./components/Blogs.vue')['default']
    ChartComponent: typeof import('./components/ChartComponent.vue')['default']
    Chatbot: typeof import('./components/Chatbot.vue')['default']
    ChatMessage: typeof import('./components/ChatMessage.vue')['default']
    CodeEditor: typeof import('./components/CodeEditor.vue')['default']
    Counter: typeof import('./components/Counter.tsx')['default']
    File: typeof import('./components/File.vue')['default']
    FileItem: typeof import('./components/FileItem.vue')['default']
    Files: typeof import('./components/Files.vue')['default']
    FunctionQueue: typeof import('./components/FunctionQueue.vue')['default']
    Functions: typeof import('./components/Functions.vue')['default']
    GoogleSearch: typeof import('./components/GoogleSearch.vue')['default']
    Input: typeof import('./components/Input.vue')['default']
    Landing: typeof import('./components/Landing.vue')['default']
    Medium: typeof import('./components/Medium.vue')['default']
    Message: typeof import('./components/Message.tsx')['default']
    Microphone: typeof import('./components/Microphone.vue')['default']
    Modal: typeof import('./components/Modal.vue')['default']
    MonacoEditor: typeof import('./components/MonacoEditor.vue')['default']
    MonacoInput: typeof import('./components/MonacoInput.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    Notifier: typeof import('./components/Notifier.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServerEvent: typeof import('./components/ServerEvent.vue')['default']
    SideBar: typeof import('./components/SideBar.vue')['default']
    Stacks: typeof import('./components/Stacks.vue')['default']
    Tabs: typeof import('./components/Tabs.vue')['default']
    TextBlock: typeof import('./components/TextBlock.vue')['default']
    Thread: typeof import('./components/Thread.vue')['default']
    Threads: typeof import('./components/Threads.vue')['default']
    TipTap: typeof import('./components/TipTap.vue')['default']
    Toolbar: typeof import('./components/Toolbar.vue')['default']
  }
}
